### ISSUE TITLE
Freecodecamp I cant Do

### ISSUE THREAD

**Issue by outintotheblue** [outintotheblue/js1#1]
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions

**Comment by ChristerNilsson** [comment]
Too many things in one issue. Please break down into at least ten smaller chunks.

**Comment by outintotheblue** [comment]
theres 6 now :D

**Comment by outintotheblue** [comment]
I just figured it out  


 if (a < 0 || b < 0) {
    return undefined;
  }
