### ISSUE TITLE
cant do 2

### ISSUE THREAD

**Issue by outintotheblue** [outintotheblue/js1#2]
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop

**Comment by ChristerNilsson** [comment]
I think it would be more helpful to state your erroneous solution here as well.
I have no clue what mistake you made as it is now.
Anyway, here is the solution:
```
var total = 0;
for (var i = 0; i < myArr.length; i++) {
  total += myArr[i];
}

```

**Comment by outintotheblue** [comment]
Ill add my wrong answers to the other ones, in here I was not using total += myArr [i] 
instead I used total as my var i.  thanks!
