### ISSUE TITLE
cant do 3

### ISSUE THREAD

**Issue by outintotheblue** [outintotheblue/js1#3]
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-parseint-function

**Comment by ChristerNilsson** [comment]
waiting for code

**Comment by outintotheblue** [comment]
function convertToInteger(str) {
  var i = parseInt("56");

  return parseInt(i);
}

convertToInteger("56");


I am only getting return 56 correct 


Then changed the number for str 

function convertToInteger(str) {
  var i = parseInt(str);

  return parseInt(i);
}

convertToInteger("56");

And worked, it  seems that I am able to do some of them now
