### ISSUE TITLE
Rover Function 2

### ISSUE THREAD

**Issue by outintotheblue** [outintotheblue/js1#7]
function moveAwayAndComeBack() {
 var a;
  for (a = 0; a < 3; a++) {
    move();// Fill in your function here.
}
}

// ---- You cannot modify these lines
move();
move();
for (let i = 0; i < 3; i++) {
  moveAwayAndComeBack();
}
move();
move();
// ++++

**Comment by ChristerNilsson** [comment]
You must make a function that steps inside and goes out the way it came in. Don't forget to point the nose in the same direction as it was before going in.

**Comment by outintotheblue** [comment]
I cant figure it out, cant make my way backwards

**Comment by ChristerNilsson** [comment]
To walk back, you turn 180 degrees, walk, and turn 180 degrees once more. This way, you have made a 360, a full circle.
